
version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: my-php-app-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: somedatabase
    volumes:
      - ./data:/var/lib/mysql
      
  dbclient:
    image: mysql:latest
    depends_on:
      - db
    command: mysql -uroot -p somepassword -hdb