
version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: my-php-app-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_DATABASE: somedatabase
    volumes:
      - my-vol:/var/lib/mysql
      
volumes:
  my-vol:
    name: my-vol